
### Get All the operations
GET http://localhost:5000/api/v1/users/


### Get single operation by ID
GET http://localhost:5000/api/v1/users/2


### Post single operation

POST http://localhost:5000/api/v1/users/ HTTP/1.1
content-type: application/json

{
  "name": "hi"
}

### Patch single operation by ID

PATCH  http://localhost:5000/api/v1/users/1 HTTP/1.1
content-type: application/json

{}

### DELETE single operation by ID

DELETE http://localhost:5000/api/v1/users/1 HTTP/1.1
 